2014-09-15 09:37:00,338 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0ABA2960> is already running or in the queue.
2014-09-15 09:37:02,767 - auto_focus.focus - INFO - Focus: 32.34, 22.88, 3.36
2014-09-15 09:37:21,417 - auto_focus.focus - INFO - Focus: 32.24, 23.18, 3.65
2014-09-15 09:37:35,308 - auto_focus.focus - INFO - Focus: 32.14, 23.24, 3.67
2014-09-15 09:38:13,497 - auto_focus.focus - INFO - Focus: 32.12, 23.22, 3.51
2014-09-15 09:39:09,898 - auto_focus.focus - INFO - Focus: 33.27, 23.11, 3.27
2014-09-15 09:41:30,868 - auto_focus.focus - INFO - Focus: 32.77, 23.09, 3.41
2014-09-15 09:41:45,459 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0ABA2960> is already running or in the queue.
2014-09-15 09:41:46,509 - auto_focus.focus - INFO - Focus: 32.27, 23.15, 2.61
2014-09-15 09:42:00,469 - auto_focus.focus - INFO - Focus: 32.33, 23.05, 2.79
2014-09-15 09:42:17,378 - auto_focus.focus - INFO - Focus: 33.56, 22.87, 2.81
2014-09-15 11:11:28,927 - auto_focus.focus - INFO - Focus: 31.27, 20.37, 4.72
2014-09-15 11:11:49,967 - auto_focus.focus - INFO - Focus: 31.33, 20.43, 4.78
2014-09-15 11:13:07,237 - auto_focus.focus - INFO - Focus: 31.40, 20.53, 4.82
2014-09-15 11:13:16,338 - auto_focus.focus - INFO - Focus: 31.30, 20.59, 4.86
2014-09-15 11:14:07,088 - auto_focus.focus - INFO - Focus: 31.30, 20.51, 4.70
2014-09-15 11:14:20,657 - auto_focus.focus - INFO - Focus: 31.38, 20.51, 4.62
2014-09-15 11:14:38,328 - auto_focus.focus - INFO - Focus: 31.38, 20.46, 4.66
2014-09-15 11:22:43,358 - auto_focus.focus - INFO - Focus: 30.98, 20.31, 4.10
2014-09-15 11:22:54,799 - auto_focus.focus - INFO - Focus: 31.13, 20.26, 4.46
2014-09-15 11:27:20,289 - auto_focus.focus - INFO - Focus: 31.33, 20.36, 4.58
2014-09-15 11:30:22,160 - auto_focus.focus - INFO - Focus: 31.43, 20.41, 4.78
2014-09-15 11:30:34,009 - auto_focus.focus - INFO - Focus: 31.38, 20.36, 4.74
2014-09-15 11:37:14,920 - auto_focus.focus - INFO - Focus: 31.43, 20.36, 4.94
2014-09-15 11:37:23,109 - auto_focus.focus - INFO - Focus: 31.48, 20.41, 4.90
2014-09-15 12:31:08,055 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0ABA2960> is already running or in the queue.
2014-09-15 12:31:15,805 - auto_focus.focus - INFO - Focus: 31.63, 20.31, 5.82
2014-09-15 12:31:25,305 - auto_focus.focus - INFO - Focus: 31.38, 20.61, 6.18
2014-09-15 12:31:33,825 - auto_focus.focus - INFO - Focus: 31.48, 20.86, 6.86
2014-09-15 12:31:42,335 - auto_focus.focus - INFO - Focus: 31.43, 20.86, 7.06
2014-09-15 12:32:20,885 - auto_focus.focus - INFO - Focus: 32.65, 21.25, 6.74
2014-09-15 12:32:38,946 - counter_trace._run - ERROR - nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 90, in _run
    counter_tr.startCounter()
  File "D:\pi3diamondnew\hardware\nidaq.py", line 203, in startCounter
    self.setCountLength(numpy.inf, max(1000, self._CountAverageLength), self._CountAverageLength)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 150, in setCountLength
    CHK(  dll.DAQmxCfgImplicitTiming( self.COTask, DAQmx_Val_ContSamps, ctypes.c_ulonglong(BufferLength))  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 12:32:51,615 - counter_trace._run - ERROR - nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 90, in _run
    counter_tr.startCounter()
  File "D:\pi3diamondnew\hardware\nidaq.py", line 203, in startCounter
    self.setCountLength(numpy.inf, max(1000, self._CountAverageLength), self._CountAverageLength)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 151, in setCountLength
    CHK(  dll.DAQmxCfgImplicitTiming( self.CITask, DAQmx_Val_ContSamps, ctypes.c_ulonglong(BufferLength))  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 12:33:16,236 - pi3diamond.<module> - INFO - Starting logger.
2014-09-15 12:33:18,236 - emod.start - INFO - Starting Job Manager.
2014-09-15 12:33:18,246 - cron.run - INFO - Starting Cron Daemon.
2014-09-15 12:33:57,226 - auto_focus.focus - INFO - Focus: 42.70, 5.24, -6.53
2014-09-15 12:34:54,686 - auto_focus.focus - INFO - Focus: 37.72, 6.38, 6.47
2014-09-15 12:35:02,865 - auto_focus.focus - INFO - Focus: 37.71, 6.53, 6.50
2014-09-15 12:38:35,155 - auto_focus.focus - INFO - Focus: 37.46, 6.64, 7.19
2014-09-15 12:38:43,196 - auto_focus.focus - INFO - Focus: 37.69, 6.47, 6.55
2014-09-15 12:38:51,315 - auto_focus.focus - INFO - Focus: 37.60, 6.30, 6.68
2014-09-15 12:40:35,766 - auto_focus.focus - INFO - Focus: 37.62, 6.34, 6.71
2014-09-15 12:41:45,596 - auto_focus.focus - INFO - Focus: 37.49, 6.25, 7.38
2014-09-15 12:41:54,536 - auto_focus.focus - INFO - Focus: 37.44, 6.36, 8.07
2014-09-15 12:42:02,476 - auto_focus.focus - INFO - Focus: 37.67, 6.51, 8.76
2014-09-15 12:42:10,437 - auto_focus.focus - INFO - Focus: 37.66, 6.70, 8.76
2014-09-15 12:44:27,417 - auto_focus.focus - INFO - Focus: 37.69, 6.45, 8.73
2014-09-15 12:44:35,326 - auto_focus.focus - INFO - Focus: 37.60, 6.56, 8.70
2014-09-15 12:44:43,397 - auto_focus.focus - INFO - Focus: 37.67, 6.59, 8.83
2014-09-15 12:45:59,346 - auto_focus.focus - INFO - Focus: 37.58, 6.38, 8.59
2014-09-15 12:46:59,836 - auto_focus.focus - INFO - Focus: 37.61, 6.53, 8.51
2014-09-15 12:49:45,357 - auto_focus.focus - INFO - Focus: 37.64, 6.60, 8.88
2014-09-15 12:49:53,937 - auto_focus.focus - INFO - Focus: 37.59, 6.55, 8.77
2014-09-15 12:50:32,157 - auto_focus.focus - INFO - Focus: 37.59, 6.58, 8.69
2014-09-15 12:50:40,197 - auto_focus.focus - INFO - Focus: 37.58, 6.49, 8.98
2014-09-15 12:51:46,038 - auto_focus.focus - INFO - Focus: 37.58, 6.54, 8.87
2014-09-15 12:51:54,128 - auto_focus.focus - INFO - Focus: 37.65, 6.57, 8.92
2014-09-15 12:53:37,828 - auto_focus.focus - INFO - Focus: 37.66, 6.61, 8.81
2014-09-15 12:53:45,858 - auto_focus.focus - INFO - Focus: 37.57, 6.64, 8.92
2014-09-15 12:53:57,568 - auto_focus.focus - INFO - Focus: 37.48, 6.55, 9.08
2014-09-15 12:54:14,618 - auto_focus.focus - INFO - Focus: 37.55, 6.62, 8.92
2014-09-15 12:55:27,207 - auto_focus.focus - INFO - Focus: 37.58, 6.57, 8.84
2014-09-15 12:55:47,138 - auto_focus.focus - INFO - Focus: 37.57, 6.64, 8.94
2014-09-15 12:56:44,767 - auto_focus.focus - INFO - Focus: 37.60, 6.63, 8.84
2014-09-15 12:58:11,358 - auto_focus.focus - INFO - Focus: 37.59, 6.54, 9.06
2014-09-15 12:59:33,898 - auto_focus.focus - INFO - Focus: 37.46, 6.73, 8.74
2014-09-15 12:59:56,989 - auto_focus.focus - INFO - Focus: 37.53, 6.52, 8.64
2014-09-15 13:00:10,358 - auto_focus.focus - INFO - Focus: 37.52, 6.63, 8.90
2014-09-15 13:01:27,019 - auto_focus.focus - INFO - Focus: 37.59, 6.62, 8.82
2014-09-15 13:03:02,109 - auto_focus.focus - INFO - Focus: 37.58, 6.61, 8.72
2014-09-15 13:04:21,029 - auto_focus.focus - INFO - Focus: 37.57, 6.60, 8.56
2014-09-15 13:05:14,390 - auto_focus.focus - INFO - Focus: 37.56, 6.63, 8.90
2014-09-15 13:05:56,440 - auto_focus.focus - INFO - Focus: 37.55, 6.62, 8.90
2014-09-15 13:06:05,470 - auto_focus.focus - INFO - Focus: 37.58, 6.61, 8.58
2014-09-15 13:06:18,420 - auto_focus.focus - INFO - Focus: 37.57, 6.56, 8.78
2014-09-15 13:06:29,490 - auto_focus.focus - INFO - Focus: 37.64, 6.63, 8.90
2014-09-15 13:09:55,269 - auto_focus.focus - INFO - Focus: 11.47, 17.24, 9.02
2014-09-15 13:10:03,740 - auto_focus.focus - INFO - Focus: 11.42, 17.07, 9.30
2014-09-15 13:10:12,440 - auto_focus.focus - INFO - Focus: 11.37, 17.02, 9.18
2014-09-15 13:15:05,051 - auto_focus.focus - INFO - Focus: 11.40, 17.05, 9.30
2014-09-15 14:21:53,536 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 9.32272727273, new value: 9.27818181818
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,566 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 17.1596153846, new value: 17.1434615385
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,576 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 9.27818181818, new value: 9.54
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,617 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 9.54, new value: 9.60545454545
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,627 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 9.60545454545, new value: 9.67090909091
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,667 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 9.67090909091, new value: 9.73636363636
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,697 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 17.1434615385, new value: 17.0769230769
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,726 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 9.73636363636, new value: 9.86727272727
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,736 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 9.86727272727, new value: 9.93272727273
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,796 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 9.93272727273, new value: 9.99818181818
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,826 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 9.99818181818, new value: 10.1290909091
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,887 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 10.1290909091, new value: 10.1945454545
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,967 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 17.0769230769, new value: 17.0103846154
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:53,996 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 10.1945454545, new value: 10.3254545455
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-15 14:21:54,006 - auto_focus.focus - INFO - Focus: 9.32, 17.16, 10.14
2014-09-15 14:22:03,917 - auto_focus.focus - INFO - Focus: 10.38, 17.24, 11.06
2014-09-15 14:22:12,586 - auto_focus.focus - INFO - Focus: 10.41, 17.39, 11.26
2014-09-15 14:22:21,236 - auto_focus.focus - INFO - Focus: 10.40, 17.38, 11.30
2014-09-15 14:22:37,117 - auto_focus.focus - INFO - Focus: 10.43, 17.37, 11.10
2014-09-15 14:24:33,467 - auto_focus.focus - INFO - Focus: 10.38, 17.36, 11.06
2014-09-15 14:24:46,447 - auto_focus.focus - INFO - Focus: 10.37, 17.47, 11.26
2014-09-15 14:26:00,157 - auto_focus.focus - INFO - Focus: 10.42, 17.44, 11.30
2014-09-15 14:27:32,878 - auto_focus.focus - INFO - Focus: 10.37, 17.43, 10.82
2014-09-15 14:27:48,838 - auto_focus.focus - INFO - Focus: 10.36, 17.38, 11.12
2014-09-15 14:28:48,628 - auto_focus.focus - INFO - Focus: 10.38, 17.40, 10.88
2014-09-15 14:29:20,727 - auto_focus.focus - INFO - Focus: 10.41, 17.15, 10.00
2014-09-15 14:29:29,628 - auto_focus.focus - INFO - Focus: 10.44, 16.94, 9.60
2014-09-15 14:29:38,278 - auto_focus.focus - INFO - Focus: 10.23, 16.69, 9.88
2014-09-15 14:29:46,927 - auto_focus.focus - INFO - Focus: 10.34, 16.64, 9.92
2014-09-15 14:29:55,598 - auto_focus.focus - INFO - Focus: 10.29, 16.39, 9.48
2014-09-15 14:30:04,108 - auto_focus.focus - INFO - Focus: 10.24, 16.38, 9.16
2014-09-15 14:30:14,618 - auto_focus.focus - INFO - Focus: 10.47, 16.29, 9.00
2014-09-15 14:30:23,298 - auto_focus.focus - INFO - Focus: 10.46, 16.24, 9.04
2014-09-15 14:33:11,308 - auto_focus.focus - INFO - Focus: 10.53, 16.31, 9.24
2014-09-15 14:33:23,108 - auto_focus.focus - INFO - Focus: 10.64, 16.38, 9.36
2014-09-15 14:34:04,638 - auto_focus.focus - INFO - Focus: 10.55, 16.37, 9.28
2014-09-15 16:08:34,237 - auto_focus.focus - INFO - Focus: 10.38, 16.24, 9.80
2014-09-15 16:08:42,858 - auto_focus.focus - INFO - Focus: 10.33, 16.27, 10.24
2014-09-15 16:08:43,407 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0BB25960> is already running or in the queue.
2014-09-15 16:08:56,398 - auto_focus.focus - INFO - Focus: 10.32, 16.02, 9.88
2014-09-15 16:09:05,417 - auto_focus.focus - INFO - Focus: 10.31, 16.21, 10.08
2014-09-15 16:09:14,098 - auto_focus.focus - INFO - Focus: 10.18, 16.20, 10.12
2014-09-15 16:09:37,878 - auto_focus.focus - INFO - Focus: 10.29, 16.23, 10.08
2014-09-15 16:09:46,447 - auto_focus.focus - INFO - Focus: 10.36, 16.26, 10.36
2014-09-15 16:10:26,987 - auto_focus.focus - INFO - Focus: 12.02, 16.83, 10.00
2014-09-15 16:10:35,818 - auto_focus.focus - INFO - Focus: 11.97, 16.94, 10.36
2014-09-15 16:10:55,757 - auto_focus.focus - INFO - Focus: 12.04, 17.17, 10.64
2014-09-15 16:11:04,427 - auto_focus.focus - INFO - Focus: 12.03, 17.28, 10.52
2014-09-15 16:11:12,997 - auto_focus.focus - INFO - Focus: 11.98, 17.35, 10.64
2014-09-15 16:11:21,497 - auto_focus.focus - INFO - Focus: 12.05, 17.42, 10.52
2014-09-15 16:25:20,039 - auto_focus.focus - INFO - Focus: 9.92, 16.31, 10.04
2014-09-15 16:25:28,869 - auto_focus.focus - INFO - Focus: 9.95, 16.26, 9.88
2014-09-15 16:25:37,539 - auto_focus.focus - INFO - Focus: 9.90, 16.25, 9.88
2014-09-15 16:27:54,079 - auto_focus.focus - INFO - Focus: 10.01, 16.28, 10.16
2014-09-15 16:29:02,359 - auto_focus.focus - INFO - Focus: 9.84, 16.47, 10.44
2014-09-15 16:30:01,460 - auto_focus.focus - INFO - Focus: 10.07, 16.50, 10.64
2014-09-15 16:30:22,980 - auto_focus.focus - INFO - Focus: 10.10, 16.41, 10.74
2014-09-15 16:30:39,559 - auto_focus.focus - INFO - Focus: 10.13, 16.56, 10.76
2014-09-15 16:34:08,490 - auto_focus.focus - INFO - Focus: 9.99, 16.40, 9.70
2014-09-15 16:34:23,460 - auto_focus.focus - INFO - Focus: 9.94, 16.39, 9.92
2014-09-15 16:35:27,990 - auto_focus.focus - INFO - Focus: 10.01, 16.38, 9.60
2014-09-15 16:36:58,329 - auto_focus.focus - INFO - Focus: 9.92, 16.33, 9.66
2014-09-15 16:38:35,171 - auto_focus.focus - INFO - Focus: 9.99, 16.32, 9.84
2014-09-15 16:41:39,831 - auto_focus.focus - INFO - Focus: 10.06, 16.15, 10.26
2014-09-15 16:41:53,030 - auto_focus.focus - INFO - Focus: 10.05, 16.06, 9.92
2014-09-15 16:43:22,030 - auto_focus.focus - INFO - Focus: 11.69, 16.76, 9.92
2014-09-15 16:44:41,252 - auto_focus.focus - INFO - Focus: 11.69, 17.04, 10.28
2014-09-15 16:44:50,871 - auto_focus.focus - INFO - Focus: 11.68, 16.95, 10.00
2014-09-15 16:44:59,752 - auto_focus.focus - INFO - Focus: 11.67, 16.94, 10.04
2014-09-15 16:45:53,492 - auto_focus.focus - INFO - Focus: 11.70, 16.97, 9.88
2014-09-15 16:46:20,681 - auto_focus.focus - INFO - Focus: 11.53, 16.96, 9.88
2014-09-15 16:46:52,092 - auto_focus.focus - INFO - Focus: 11.68, 17.07, 10.16
2014-09-15 16:46:52,911 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0BB25960> is already running or in the queue.
2014-09-15 16:47:08,232 - auto_focus.focus - INFO - Focus: 11.59, 17.10, 10.20
2014-09-15 16:47:26,022 - auto_focus.focus - INFO - Focus: 11.66, 16.97, 10.00
2014-09-15 16:47:35,361 - auto_focus.focus - INFO - Focus: 11.73, 16.92, 10.04
2014-09-15 16:47:50,431 - auto_focus.focus - INFO - Focus: 11.64, 16.95, 10.72
2014-09-15 16:47:59,611 - auto_focus.focus - INFO - Focus: 11.67, 17.10, 10.36
2014-09-15 16:48:08,742 - auto_focus.focus - INFO - Focus: 11.74, 17.09, 10.48
2014-09-16 18:12:58,321 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x071E5420> is already running or in the queue.
2014-09-16 18:15:06,000 - auto_focus.focus - INFO - Focus: 21.47, 13.55, 8.37
2014-09-16 18:15:15,010 - auto_focus.focus - INFO - Focus: 21.26, 13.66, 8.09
2014-09-16 18:15:27,411 - auto_focus.focus - INFO - Focus: 21.33, 13.57, 8.15
2014-09-16 18:15:40,040 - auto_focus.focus - INFO - Focus: 21.28, 13.64, 8.33
2014-09-16 18:18:20,740 - auto_focus.focus - INFO - Focus: 16.82, 14.12, 8.13
2014-09-16 18:18:29,621 - auto_focus.focus - INFO - Focus: 16.81, 14.07, 8.05
2014-09-16 18:19:18,430 - auto_focus.focus - INFO - Focus: 35.25, 5.60, 7.69
2014-09-16 18:19:28,171 - auto_focus.focus - INFO - Focus: 35.28, 5.59, 7.57
2014-09-16 18:20:25,430 - auto_focus.focus - INFO - Focus: 36.98, 5.48, 7.61
2014-09-16 18:20:35,101 - auto_focus.focus - INFO - Focus: 37.05, 5.43, 7.33
2014-09-16 18:23:13,191 - auto_focus.focus - INFO - Focus: 37.08, 5.42, 7.45
2014-09-16 18:23:22,361 - auto_focus.focus - INFO - Focus: 37.03, 5.33, 7.41
2014-09-16 18:23:38,822 - auto_focus.focus - INFO - Focus: 37.10, 5.08, 6.73
2014-09-16 18:23:47,891 - auto_focus.focus - INFO - Focus: 37.13, 5.19, 6.93
2014-09-16 18:23:58,522 - auto_focus.focus - INFO - Focus: 37.20, 5.26, 6.73
2014-09-16 18:31:36,232 - auto_focus.focus - INFO - Focus: 37.07, 5.26, 7.41
2014-09-16 18:31:44,941 - auto_focus.focus - INFO - Focus: 37.18, 5.41, 7.41
2014-09-16 18:31:53,582 - auto_focus.focus - INFO - Focus: 37.17, 5.40, 7.45
2014-09-16 18:37:04,443 - auto_focus.focus - INFO - Focus: 38.28, 4.48, 7.49
2014-09-16 18:37:13,292 - auto_focus.focus - INFO - Focus: 38.27, 4.51, 7.49
2014-09-16 18:39:19,023 - auto_focus.focus - INFO - Focus: 37.17, 5.28, 7.41
2014-09-16 18:39:27,842 - auto_focus.focus - INFO - Focus: 37.20, 5.35, 7.53
2014-09-16 18:42:39,282 - auto_focus.focus - INFO - Focus: 37.15, 5.31, 7.49
2014-09-16 18:45:08,532 - auto_focus.focus - INFO - Focus: 37.14, 5.34, 7.09
2014-09-17 14:55:16,282 - auto_focus.focus - INFO - Focus: 4.89, 12.41, 9.06
2014-09-17 14:55:25,013 - auto_focus.focus - INFO - Focus: 4.84, 12.52, 9.06
2014-09-17 14:56:42,592 - auto_focus.focus - INFO - Focus: 41.70, 25.81, 10.06
2014-09-17 14:56:51,273 - auto_focus.focus - INFO - Focus: 41.81, 25.88, 10.50
2014-09-17 14:58:40,013 - auto_focus.focus - INFO - Focus: 33.00, 21.38, 8.68
2014-09-17 14:58:48,582 - auto_focus.focus - INFO - Focus: 33.03, 21.57, 8.88
2014-09-17 14:58:57,153 - auto_focus.focus - INFO - Focus: 32.82, 21.40, 8.40
2014-09-17 15:00:10,753 - auto_focus.focus - INFO - Focus: 47.73, 28.59, 8.76
2014-09-17 15:00:19,342 - auto_focus.focus - INFO - Focus: 47.56, 28.74, 8.88
2014-09-17 15:00:27,384 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 47.6735739351, new value: 47.5435739351
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,394 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 28.4944168454, new value: 28.4661849385
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,404 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 28.4661849385, new value: 28.277068985
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,414 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 47.5435739351, new value: 47.3555129025
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,424 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 47.3555129025, new value: 47.1674518699
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,434 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 28.277068985, new value: 28.0879530315
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,453 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 47.1674518699, new value: 46.9793908374
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,463 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 46.9793908374, new value: 46.7913298048
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,483 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 28.0879530315, new value: 27.898837078
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,493 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 46.7913298048, new value: 46.227146707
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,503 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 27.898837078, new value: 27.5206051711
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,523 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 46.227146707, new value: 45.6629636092
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,553 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 27.5206051711, new value: 27.3314892176
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,563 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 45.6629636092, new value: 45.286841544
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,573 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 27.3314892176, new value: 26.9532573106
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,584 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 45.286841544, new value: 44.9107194789
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,604 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 26.9532573106, new value: 26.7641413571
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,614 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 44.9107194789, new value: 44.3465363811
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,624 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 26.7641413571, new value: 26.5750254036
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,644 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 44.3465363811, new value: 43.5942922507
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,654 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 26.5750254036, new value: 26.1967934967
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,674 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 43.5942922507, new value: 43.0301091529
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,684 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 26.1967934967, new value: 26.0076775432
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,694 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 43.0301091529, new value: 42.8420481204
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:27,713 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 42.8420481204, new value: 42.6539870878
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 15:00:28,053 - auto_focus.focus - INFO - Focus: 47.67, 28.49, 8.24
2014-09-17 15:00:38,864 - auto_focus.focus - INFO - Focus: 41.68, 25.62, 9.24
2014-09-17 15:00:47,553 - auto_focus.focus - INFO - Focus: 41.63, 25.85, 10.24
2014-09-17 15:00:56,053 - auto_focus.focus - INFO - Focus: 41.66, 26.04, 10.28
2014-09-17 15:01:20,223 - auto_focus.focus - INFO - Focus: 36.85, 30.32, 9.28
2014-09-17 15:01:27,384 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <chaco.data_range_1d.DataRange1D object at 0x071EEBA0>, trait: _low_value, old value: 0.0, new value: -0.383877159309
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 480, in update_axis_lv
    self.y1 = self.figure.value_range.low
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'y1' trait of a Confocal instance must be 0.0 <= a floating point number <= 50.0, but a value of -0.3838771593090211 <type 'float'> was specified.
2014-09-17 15:01:55,773 - auto_focus.focus - INFO - Focus: 1.24, 2.53, 9.56
2014-09-17 15:02:04,384 - auto_focus.focus - INFO - Focus: 1.23, 2.56, 9.84
2014-09-17 15:02:13,513 - auto_focus.focus - INFO - Focus: 1.22, 2.59, 9.52
2014-09-17 15:05:29,033 - auto_focus.focus - INFO - Focus: 9.83, 33.81, 8.88
2014-09-17 15:05:37,763 - auto_focus.focus - INFO - Focus: 9.82, 33.80, 8.92
2014-09-17 15:07:33,844 - auto_focus.focus - INFO - Focus: 9.65, 33.99, 8.64
2014-09-17 15:07:42,634 - auto_focus.focus - INFO - Focus: 9.80, 33.90, 8.76
2014-09-17 15:08:58,803 - auto_focus.focus - INFO - Focus: 9.27, 33.01, 8.69
2014-09-17 15:09:07,323 - auto_focus.focus - INFO - Focus: 9.42, 33.04, 8.61
2014-09-17 15:17:37,644 - auto_focus.focus - INFO - Focus: 9.00, 33.44, 11.28
2014-09-17 15:18:07,265 - auto_focus.focus - INFO - Focus: 16.92, 4.80, 10.32
2014-09-17 15:18:16,404 - auto_focus.focus - INFO - Focus: 16.91, 4.91, 10.16
2014-09-17 15:22:20,525 - auto_focus.focus - INFO - Focus: 17.14, 5.06, 10.20
2014-09-17 15:22:29,214 - auto_focus.focus - INFO - Focus: 17.29, 5.29, 10.72
2014-09-17 15:22:38,414 - auto_focus.focus - INFO - Focus: 17.52, 5.48, 10.08
2014-09-17 15:22:49,464 - auto_focus.focus - INFO - Focus: 17.75, 5.63, 10.00
2014-09-17 15:23:00,605 - auto_focus.focus - INFO - Focus: 17.98, 5.62, 9.76
2014-09-17 15:23:09,335 - auto_focus.focus - INFO - Focus: 18.13, 5.57, 9.76
2014-09-17 15:23:18,365 - auto_focus.focus - INFO - Focus: 18.36, 5.56, 9.72
2014-09-17 15:23:27,184 - auto_focus.focus - INFO - Focus: 18.35, 5.51, 9.76
2014-09-17 15:23:37,055 - auto_focus.focus - INFO - Focus: 18.54, 5.70, 9.80
2014-09-17 15:34:50,216 - auto_focus.focus - INFO - Focus: 20.15, 26.01, 9.54
2014-09-17 15:34:58,835 - auto_focus.focus - INFO - Focus: 20.02, 26.08, 9.58
2014-09-17 15:35:07,426 - auto_focus.focus - INFO - Focus: 20.21, 25.87, 9.34
2014-09-17 15:35:16,115 - auto_focus.focus - INFO - Focus: 20.32, 26.06, 9.62
2014-09-17 15:37:46,737 - auto_focus.focus - INFO - Focus: 23.02, 5.31, 8.66
2014-09-17 15:37:55,338 - auto_focus.focus - INFO - Focus: 23.13, 5.06, 8.26
2014-09-17 15:38:03,808 - auto_focus.focus - INFO - Focus: 23.04, 4.93, 8.46
2014-09-17 15:38:12,368 - auto_focus.focus - INFO - Focus: 22.91, 4.76, 8.66
2014-09-17 15:38:21,007 - auto_focus.focus - INFO - Focus: 23.10, 4.95, 8.50
2014-09-17 15:38:29,538 - auto_focus.focus - INFO - Focus: 23.13, 4.86, 8.62
2014-09-17 15:38:38,138 - auto_focus.focus - INFO - Focus: 23.16, 4.97, 8.46
2014-09-17 15:41:31,878 - auto_focus.focus - INFO - Focus: 10.79, 12.67, 9.06
2014-09-17 15:41:40,608 - auto_focus.focus - INFO - Focus: 10.78, 12.74, 9.06
2014-09-17 15:44:01,348 - auto_focus.focus - INFO - Focus: 10.97, 12.77, 9.18
2014-09-17 15:46:20,177 - auto_focus.focus - INFO - Focus: 10.85, 12.73, 9.02
2014-09-17 15:47:20,868 - auto_focus.focus - INFO - Focus: 11.04, 12.76, 9.38
2014-09-17 15:47:29,628 - auto_focus.focus - INFO - Focus: 11.03, 12.59, 9.22
2014-09-17 15:47:38,318 - auto_focus.focus - INFO - Focus: 11.02, 12.78, 9.34
2014-09-17 15:47:47,048 - auto_focus.focus - INFO - Focus: 11.05, 12.81, 9.62
2014-09-17 15:48:35,959 - auto_focus.focus - INFO - Focus: 11.08, 12.80, 9.46
2014-09-17 15:49:18,979 - auto_focus.focus - INFO - Focus: 11.07, 12.74, 9.22
2014-09-17 15:49:27,739 - auto_focus.focus - INFO - Focus: 11.06, 12.73, 9.42
2014-09-17 15:49:43,348 - auto_focus.focus - INFO - Focus: 11.05, 12.76, 9.38
2014-09-17 15:50:51,059 - auto_focus.focus - INFO - Focus: 11.12, 12.71, 9.30
2014-09-17 15:51:00,989 - auto_focus.focus - INFO - Focus: 11.07, 12.74, 9.34
2014-09-17 15:51:43,539 - auto_focus.focus - INFO - Focus: 11.14, 12.73, 9.38
2014-09-17 15:51:52,759 - auto_focus.focus - INFO - Focus: 11.13, 12.68, 9.26
2014-09-17 15:52:14,168 - auto_focus.focus - INFO - Focus: 11.16, 12.63, 9.32
2014-09-17 15:52:25,789 - auto_focus.focus - INFO - Focus: 11.11, 12.58, 9.24
2014-09-17 15:52:50,989 - auto_focus.focus - INFO - Focus: 10.86, 12.45, 8.80
2014-09-17 15:52:59,868 - auto_focus.focus - INFO - Focus: 10.81, 12.36, 8.84
2014-09-17 15:53:57,509 - auto_focus.focus - INFO - Focus: 10.96, 12.47, 8.84
2014-09-17 15:54:07,618 - auto_focus.focus - INFO - Focus: 10.91, 12.42, 8.84
2014-09-17 15:58:59,819 - auto_focus.focus - INFO - Focus: 10.82, 12.57, 9.12
2014-09-17 15:59:08,428 - auto_focus.focus - INFO - Focus: 10.57, 12.72, 9.32
2014-09-17 15:59:18,489 - auto_focus.focus - INFO - Focus: 10.32, 12.47, 8.76
2014-09-17 15:59:39,178 - auto_focus.focus - INFO - Focus: 11.26, 12.72, 9.20
2014-09-17 15:59:48,188 - auto_focus.focus - INFO - Focus: 11.41, 12.63, 9.64
2014-09-17 15:59:56,890 - auto_focus.focus - INFO - Focus: 11.20, 12.58, 9.44
2014-09-17 16:00:06,009 - auto_focus.focus - INFO - Focus: 10.99, 12.37, 9.16
2014-09-17 16:01:03,650 - auto_focus.focus - INFO - Focus: 12.88, 11.82, 9.36
2014-09-17 16:40:25,904 - auto_focus.focus - INFO - Focus: 13.42, 11.35, 8.50
2014-09-17 16:40:35,174 - auto_focus.focus - INFO - Focus: 13.65, 11.54, 8.22
2014-09-17 16:40:43,773 - auto_focus.focus - INFO - Focus: 13.88, 11.69, 8.74
2014-09-17 16:40:52,473 - auto_focus.focus - INFO - Focus: 13.87, 11.80, 8.66
2014-09-17 16:42:05,963 - auto_focus.focus - INFO - Focus: 13.55, 12.51, 8.66
2014-09-17 16:43:42,374 - auto_focus.focus - INFO - Focus: 14.54, 13.43, 8.66
2014-09-17 16:43:51,094 - auto_focus.focus - INFO - Focus: 14.57, 13.38, 8.70
2014-09-17 16:44:25,763 - auto_focus.focus - INFO - Focus: 14.52, 13.41, 8.82
2014-09-17 16:57:02,095 - auto_focus.focus - INFO - Focus: 15.10, 10.49, 8.50
2014-09-17 17:10:49,085 - auto_focus.focus - INFO - Focus: 15.20, 10.33, 8.50
2014-09-17 17:10:58,266 - auto_focus.focus - INFO - Focus: 15.39, 10.16, 8.46
2014-09-17 17:11:06,976 - auto_focus.focus - INFO - Focus: 15.18, 10.27, 8.50
2014-09-17 17:11:15,246 - auto_focus.focus - INFO - Focus: 15.17, 10.34, 8.50
2014-09-17 17:14:21,177 - auto_focus.focus - INFO - Focus: 15.22, 10.19, 8.39
2014-09-17 17:14:29,746 - auto_focus.focus - INFO - Focus: 15.21, 10.30, 8.43
2014-09-17 17:14:38,637 - auto_focus.focus - INFO - Focus: 15.24, 10.29, 8.39
2014-09-17 17:18:59,236 - auto_focus.focus - INFO - Focus: 15.16, 9.98, 8.03
2014-09-17 17:19:07,776 - auto_focus.focus - INFO - Focus: 15.19, 10.09, 8.23
2014-09-17 17:19:19,756 - auto_focus.focus - INFO - Focus: 15.22, 10.20, 8.43
2014-09-17 17:38:40,789 - auto_focus.focus - INFO - Focus: 15.22, 10.16, 8.40
2014-09-17 17:38:49,509 - auto_focus.focus - INFO - Focus: 15.25, 10.19, 8.40
2014-09-17 17:41:42,240 - auto_focus.focus - INFO - Focus: 15.20, 10.02, 8.30
2014-09-17 17:41:51,049 - auto_focus.focus - INFO - Focus: 15.27, 10.13, 8.42
2014-09-17 17:41:59,910 - auto_focus.focus - INFO - Focus: 15.26, 10.12, 8.46
2014-09-17 17:55:45,821 - auto_focus.focus - INFO - Focus: 15.30, 9.89, 7.66
2014-09-17 17:55:54,440 - auto_focus.focus - INFO - Focus: 15.29, 9.88, 7.66
2014-09-17 17:58:55,881 - auto_focus.focus - INFO - Focus: 33.55, 26.51, 8.66
2014-09-17 17:59:04,461 - auto_focus.focus - INFO - Focus: 33.66, 26.50, 9.42
2014-09-17 17:59:12,832 - counter_trace._run - ERROR - nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 90, in _run
    counter_tr.startCounter()
  File "D:\pi3diamondnew\hardware\nidaq.py", line 203, in startCounter
    self.setCountLength(numpy.inf, max(1000, self._CountAverageLength), self._CountAverageLength)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 150, in setCountLength
    CHK(  dll.DAQmxCfgImplicitTiming( self.COTask, DAQmx_Val_ContSamps, ctypes.c_ulonglong(BufferLength))  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:15,431 - counter_trace._run - ERROR - nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 90, in _run
    counter_tr.startCounter()
  File "D:\pi3diamondnew\hardware\nidaq.py", line 203, in startCounter
    self.setCountLength(numpy.inf, max(1000, self._CountAverageLength), self._CountAverageLength)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 151, in setCountLength
    CHK(  dll.DAQmxCfgImplicitTiming( self.CITask, DAQmx_Val_ContSamps, ctypes.c_ulonglong(BufferLength))  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,022 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 33.6095722512, new value: 33.4795722512
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,032 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 26.5327164256, new value: 26.5627164256
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,042 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 33.4795722512, new value: 32.8537557057
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,052 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 26.5627164256, new value: 26.4044165661
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,072 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 32.8537557057, new value: 31.6021226149
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,092 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 26.4044165661, new value: 26.0878168471
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,101 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 31.6021226149, new value: 30.350489524
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,131 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 26.0878168471, new value: 25.9295169876
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,161 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 30.350489524, new value: 30.0375812513
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:22,171 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 25.9295169876, new value: 25.771217128
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:24,312 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 30.0375812513, new value: 29.7246729786
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:24,322 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 25.771217128, new value: 25.2963175495
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:24,332 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 29.7246729786, new value: 29.2553105695
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:24,342 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 25.2963175495, new value: 24.821417971
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:24,361 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 29.2553105695, new value: 29.0988564332
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:24,381 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 24.821417971, new value: 24.6631181115
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,201 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 29.0988564332, new value: 29.2553105695
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,242 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 29.2553105695, new value: 29.4117647059
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,302 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 29.4117647059, new value: 29.5682188422
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,302 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 24.6631181115, new value: 24.821417971
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,312 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 29.5682188422, new value: 29.881127115
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,322 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 29.881127115, new value: 30.0375812513
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,361 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 30.0375812513, new value: 30.1940353877
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,421 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 30.1940353877, new value: 30.350489524
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,461 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 30.350489524, new value: 30.5069436604
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,492 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 30.5069436604, new value: 30.6633977967
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,502 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 30.6633977967, new value: 30.8198519331
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,512 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 30.8198519331, new value: 30.9763060695
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,572 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 30.9763060695, new value: 31.1327602058
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,582 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: y, old value: 24.821417971, new value: 24.9797178305
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:27,611 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x071E5420>, trait: x, old value: 31.1327602058, new value: 31.2892143422
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 121, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 435, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 252, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-17 17:59:42,911 - pi3diamond.<module> - INFO - Starting logger.
2014-09-17 17:59:44,721 - emod.start - INFO - Starting Job Manager.
2014-09-17 17:59:44,721 - cron.run - INFO - Starting Cron Daemon.
2014-09-17 18:00:44,611 - auto_focus.focus - INFO - Focus: 42.46, 5.32, -5.60
2014-09-17 18:03:13,312 - auto_focus.focus - INFO - Focus: 23.34, 11.14, 8.04
2014-09-17 18:03:22,631 - auto_focus.focus - INFO - Focus: 23.09, 11.29, 8.39
2014-09-17 18:04:01,252 - auto_focus.focus - INFO - Focus: 25.08, 11.69, 8.13
2014-09-17 18:04:13,552 - auto_focus.focus - INFO - Focus: 24.95, 11.76, 8.32
2014-09-17 18:04:41,002 - auto_focus.focus - INFO - Focus: 24.94, 3.53, 8.91
2014-09-17 18:04:50,111 - auto_focus.focus - INFO - Focus: 24.97, 3.52, 9.02
2014-09-17 18:05:52,701 - auto_focus.focus - INFO - Focus: 25.27, 8.39, 8.91
2014-09-17 18:08:55,351 - auto_focus.focus - INFO - Focus: 20.96, 11.67, 8.35
2014-09-17 18:09:03,611 - auto_focus.focus - INFO - Focus: 20.99, 11.58, 8.19
2014-09-17 18:09:31,971 - auto_focus.focus - INFO - Focus: 24.97, 3.41, 8.56
2014-09-17 18:09:40,351 - auto_focus.focus - INFO - Focus: 25.00, 3.48, 8.85
2014-09-17 18:09:48,451 - auto_focus.focus - INFO - Focus: 24.99, 3.51, 8.82
2014-09-17 18:10:39,042 - auto_focus.focus - INFO - Focus: 24.75, 3.28, 8.10
2014-09-17 18:10:47,552 - auto_focus.focus - INFO - Focus: 24.74, 3.23, 8.13
2014-09-17 18:10:55,513 - auto_focus.focus - INFO - Focus: 24.73, 3.30, 8.05
2014-09-17 18:11:35,403 - auto_focus.focus - INFO - Focus: 24.72, 3.17, 8.48
2014-09-17 18:11:44,943 - auto_focus.focus - INFO - Focus: 24.75, 3.24, 8.51
2014-09-17 18:12:29,003 - auto_focus.focus - INFO - Focus: 24.78, 3.27, 7.95
2014-09-17 18:12:39,102 - auto_focus.focus - INFO - Focus: 24.77, 3.26, 8.13
2014-09-17 18:13:18,993 - auto_focus.focus - INFO - Focus: 24.76, 3.21, 8.03
2014-09-17 18:14:52,332 - auto_focus.focus - INFO - Focus: 24.79, 3.24, 7.87
2014-09-17 18:16:00,112 - auto_focus.focus - INFO - Focus: 24.78, 3.23, 7.89
2014-09-17 18:16:23,683 - auto_focus.focus - INFO - Focus: 24.77, 3.26, 7.92
2014-09-17 18:17:11,463 - auto_focus.focus - INFO - Focus: 24.76, 3.21, 7.95
2014-09-17 18:17:20,473 - auto_focus.focus - INFO - Focus: 24.79, 3.24, 7.84
2014-09-17 18:18:23,622 - auto_focus.focus - INFO - Focus: 24.78, 3.23, 7.73
2014-09-17 18:18:55,163 - auto_focus.focus - INFO - Focus: 24.77, 3.14, 7.65
2014-09-17 18:19:04,572 - auto_focus.focus - INFO - Focus: 24.76, 3.21, 7.76
2014-09-17 18:20:20,003 - auto_focus.focus - INFO - Focus: 24.79, 3.24, 7.60
2014-09-18 09:42:44,187 - auto_focus.focus - INFO - Focus: 29.13, 3.58, 8.76
2014-09-18 09:42:52,288 - auto_focus.focus - INFO - Focus: 28.92, 3.77, 9.51
2014-09-18 09:43:01,517 - auto_focus.focus - INFO - Focus: 28.83, 3.60, 9.43
2014-09-18 09:43:10,878 - auto_focus.focus - INFO - Focus: 28.90, 3.63, 9.72
2014-09-18 09:43:18,977 - auto_focus.focus - INFO - Focus: 28.89, 3.78, 9.75
2014-09-18 09:43:27,148 - auto_focus.focus - INFO - Focus: 28.88, 3.69, 9.78
2014-09-18 09:47:59,848 - auto_focus.focus - INFO - Focus: 28.91, 3.80, 9.43
2014-09-18 09:48:07,937 - auto_focus.focus - INFO - Focus: 28.86, 3.83, 9.35
2014-09-18 10:08:36,279 - auto_focus.focus - INFO - Focus: 38.25, 4.06, 4.96
2014-09-18 10:08:44,650 - auto_focus.focus - INFO - Focus: 38.36, 3.97, 5.23
2014-09-18 11:19:35,048 - auto_focus.focus - INFO - Focus: 35.61, 3.29, 4.03
2014-09-18 11:19:43,108 - auto_focus.focus - INFO - Focus: 35.56, 3.32, 4.78
2014-09-18 11:19:51,747 - auto_focus.focus - INFO - Focus: 35.55, 3.31, 5.53
2014-09-18 11:19:56,457 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <chaco.data_range_1d.DataRange1D object at 0x07204C30>, trait: _low_value, old value: 0.0, new value: -0.287907869482
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 480, in update_axis_lv
    self.y1 = self.figure.value_range.low
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'y1' trait of a Confocal instance must be 0.0 <= a floating point number <= 50.0, but a value of -0.28790786948176583 <type 'float'> was specified.
2014-09-18 11:20:51,778 - auto_focus.focus - INFO - Focus: 41.76, 3.71, 6.20
2014-09-18 11:21:04,138 - auto_focus.focus - INFO - Focus: 41.75, 3.70, 6.12
2014-09-18 11:21:13,687 - auto_focus.focus - INFO - Focus: 41.78, 3.69, 6.12
2014-09-18 11:22:01,917 - auto_focus.focus - INFO - Focus: 41.73, 3.68, 6.31
2014-09-18 11:22:10,088 - auto_focus.focus - INFO - Focus: 41.76, 3.71, 5.91
2014-09-18 11:22:50,767 - auto_focus.focus - INFO - Focus: 41.73, 3.77, 6.01
2014-09-18 11:23:40,927 - auto_focus.focus - INFO - Focus: 41.79, 3.65, 5.81
2014-09-18 11:23:56,447 - auto_focus.focus - INFO - Focus: 41.67, 2.90, 6.01
2014-09-18 11:25:26,717 - auto_focus.focus - INFO - Focus: 41.79, 2.24, 6.21
2014-09-18 11:25:43,697 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0AEDB9F0> is already running or in the queue.
2014-09-18 11:25:44,778 - auto_focus.focus - INFO - Focus: 41.83, 3.64, 5.91
2014-09-18 11:25:49,477 - auto_focus.focus - INFO - Focus: 41.75, 3.65, 5.81
2014-09-18 11:26:34,667 - auto_focus.focus - INFO - Focus: 41.76, 3.66, 6.01
2014-09-18 11:26:40,417 - auto_focus.focus - INFO - Focus: 41.77, 3.67, 6.11
2014-09-18 11:27:34,088 - auto_focus.focus - INFO - Focus: 41.74, 3.68, 6.11
2014-09-18 11:27:38,717 - auto_focus.focus - INFO - Focus: 41.75, 3.69, 6.11
2014-09-18 11:28:13,237 - auto_focus.focus - INFO - Focus: 41.76, 3.70, 6.41
2014-09-18 11:28:18,108 - auto_focus.focus - INFO - Focus: 41.77, 3.71, 6.21
2014-09-18 11:28:23,747 - auto_focus.focus - INFO - Focus: 41.78, 3.63, 6.31
2014-09-18 11:29:03,428 - auto_focus.focus - INFO - Focus: 41.74, 3.64, 6.31
2014-09-18 11:29:08,759 - auto_focus.focus - INFO - Focus: 41.84, 3.74, 6.31
2014-09-18 11:29:46,459 - auto_focus.focus - INFO - Focus: 41.76, 3.75, 6.21
2014-09-18 11:29:51,309 - auto_focus.focus - INFO - Focus: 41.77, 3.67, 6.11
2014-09-18 11:29:59,918 - auto_focus.focus - INFO - Focus: 41.78, 3.68, 6.01
2014-09-18 11:30:42,549 - auto_focus.focus - INFO - Focus: 41.74, 3.68, 6.11
2014-09-18 11:30:47,319 - auto_focus.focus - INFO - Focus: 41.75, 3.69, 6.11
2014-09-18 11:31:34,188 - auto_focus.focus - INFO - Focus: 41.76, 3.61, 5.91
2014-09-18 11:31:38,979 - auto_focus.focus - INFO - Focus: 41.77, 3.62, 6.01
2014-09-18 11:32:53,469 - auto_focus.focus - INFO - Focus: 41.74, 3.68, 6.11
2014-09-18 11:33:29,188 - auto_focus.focus - INFO - Focus: 41.75, 3.69, 5.91
2014-09-18 11:33:34,948 - auto_focus.focus - INFO - Focus: 41.76, 3.61, 5.71
2014-09-18 11:35:05,539 - auto_focus.focus - INFO - Focus: 41.65, 3.73, 5.71
2014-09-18 11:35:10,638 - auto_focus.focus - INFO - Focus: 41.75, 3.65, 6.21
2014-09-18 11:35:15,789 - auto_focus.focus - INFO - Focus: 41.76, 3.66, 5.81
2014-09-18 11:35:21,638 - auto_focus.focus - INFO - Focus: 41.77, 3.67, 5.91
2014-09-18 11:35:49,598 - auto_focus.focus - INFO - Focus: 41.74, 3.73, 6.21
2014-09-18 11:37:38,799 - auto_focus.focus - INFO - Focus: 41.74, 3.64, 5.91
2014-09-18 11:37:43,658 - auto_focus.focus - INFO - Focus: 41.75, 3.65, 5.91
2014-09-18 11:38:14,138 - auto_focus.focus - INFO - Focus: 41.74, 3.68, 5.91
2014-09-18 11:38:19,009 - auto_focus.focus - INFO - Focus: 41.75, 3.60, 5.91
2014-09-18 11:38:46,408 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <chaco.data_range_1d.DataRange1D object at 0x07204C30>, trait: _low_value, old value: 0.0, new value: -0.0216278595977
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 480, in update_axis_lv
    self.y1 = self.figure.value_range.low
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'y1' trait of a Confocal instance must be 0.0 <= a floating point number <= 50.0, but a value of -0.021627859597718783 <type 'float'> was specified.
2014-09-18 11:39:43,499 - auto_focus.focus - INFO - Focus: 41.76, 3.70, 6.01
2014-09-18 11:39:48,168 - auto_focus.focus - INFO - Focus: 41.77, 3.62, 6.11
2014-09-18 11:41:27,160 - auto_focus.focus - INFO - Focus: 41.69, 3.72, 6.01
2014-09-18 11:41:31,920 - auto_focus.focus - INFO - Focus: 41.70, 3.73, 5.91
2014-09-18 11:42:26,460 - auto_focus.focus - INFO - Focus: 41.71, 3.74, 6.41
2014-09-18 11:42:33,349 - auto_focus.focus - INFO - Focus: 41.81, 3.75, 6.61
2014-09-18 11:42:45,009 - auto_focus.focus - INFO - Focus: 42.00, 3.76, 6.41
2014-09-18 11:42:49,720 - auto_focus.focus - INFO - Focus: 41.92, 3.68, 6.31
2014-09-18 11:42:54,369 - auto_focus.focus - INFO - Focus: 41.93, 3.78, 6.31
2014-09-18 11:42:59,200 - auto_focus.focus - INFO - Focus: 41.94, 3.70, 6.51
2014-09-18 11:43:41,900 - auto_focus.focus - INFO - Focus: 42.00, 3.72, 6.51
2014-09-18 11:43:46,809 - auto_focus.focus - INFO - Focus: 42.01, 3.82, 6.41
2014-09-18 11:43:53,230 - auto_focus.focus - INFO - Focus: 41.93, 3.74, 6.31
2014-09-18 11:43:58,710 - auto_focus.focus - INFO - Focus: 41.94, 3.75, 6.31
2014-09-18 11:46:40,009 - auto_focus.focus - INFO - Focus: 41.95, 4.03, 7.20
2014-09-18 11:46:45,619 - auto_focus.focus - INFO - Focus: 41.96, 4.13, 7.20
2014-09-18 11:47:15,089 - auto_focus.focus - INFO - Focus: 42.92, 2.48, 7.40
2014-09-18 11:47:20,140 - auto_focus.focus - INFO - Focus: 42.93, 2.58, 7.40
2014-09-18 11:47:30,410 - auto_focus.focus - INFO - Focus: 42.94, 2.50, 7.50
2014-09-18 11:47:40,569 - auto_focus.focus - INFO - Focus: 42.86, 2.69, 7.40
2014-09-18 11:48:35,700 - auto_focus.focus - INFO - Focus: 42.69, 2.88, 7.00
2014-09-18 11:48:44,009 - auto_focus.focus - INFO - Focus: 42.52, 2.89, 6.80
2014-09-18 11:50:28,450 - auto_focus.focus - INFO - Focus: 39.21, 4.64, 6.01
2014-09-18 11:50:36,539 - auto_focus.focus - INFO - Focus: 39.22, 4.65, 6.11
2014-09-18 11:52:22,240 - auto_focus.focus - INFO - Focus: 39.21, 1.54, 6.20
2014-09-18 11:52:29,329 - auto_focus.focus - INFO - Focus: 39.22, 1.64, 6.20
2014-09-18 11:53:49,270 - auto_focus.focus - INFO - Focus: 40.80, 3.16, 6.40
2014-09-18 11:53:54,111 - auto_focus.focus - INFO - Focus: 41.08, 2.99, 6.50
2014-09-18 11:54:50,680 - auto_focus.focus - INFO - Focus: 48.60, 2.23, 6.40
2014-09-18 11:54:55,421 - auto_focus.focus - INFO - Focus: 48.61, 2.33, 6.50
2014-09-18 11:56:29,391 - auto_focus.focus - INFO - Focus: 48.53, 2.25, 6.40
2014-09-18 11:57:06,790 - auto_focus.focus - INFO - Focus: 48.54, 2.35, 6.40
2014-09-18 11:59:26,260 - auto_focus.focus - INFO - Focus: 41.96, 0.66, 5.19
2014-09-18 11:59:31,421 - auto_focus.focus - INFO - Focus: 42.15, 0.31, 4.79
2014-09-18 11:59:37,270 - auto_focus.focus - INFO - Focus: 41.98, 0.36, 4.40
2014-09-18 11:59:42,450 - auto_focus.focus - INFO - Focus: 41.99, 0.28, 4.40
2014-09-18 12:00:19,750 - auto_focus.focus - INFO - Focus: 43.46, 1.94, 4.10
2014-09-18 12:00:25,661 - auto_focus.focus - INFO - Focus: 43.47, 1.95, 4.50
2014-09-18 12:01:45,020 - auto_focus.focus - INFO - Focus: 43.58, 1.99, 4.47
2014-09-18 12:01:50,250 - auto_focus.focus - INFO - Focus: 43.59, 1.82, 4.27
2014-09-18 12:01:59,720 - auto_focus.focus - INFO - Focus: 43.69, 1.92, 4.17
2014-09-18 12:02:04,401 - auto_focus.focus - INFO - Focus: 43.61, 1.84, 4.37
2014-09-18 13:36:08,938 - auto_focus.focus - INFO - Focus: 45.90, 2.27, 4.54
2014-09-18 13:36:19,459 - auto_focus.focus - INFO - Focus: 45.95, 2.32, 4.54
2014-09-18 13:37:21,158 - auto_focus.focus - INFO - Focus: 40.51, 3.38, 4.54
2014-09-18 13:37:29,908 - auto_focus.focus - INFO - Focus: 40.46, 3.38, 4.54
2014-09-18 13:38:40,168 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 13:38:46,348 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 13:38:56,029 - auto_focus.focus - INFO - Focus: 40.71, 3.63, 4.75
2014-09-18 13:39:03,739 - auto_focus.focus - INFO - Focus: 40.66, 3.68, 4.78
2014-09-18 13:49:23,970 - auto_focus.focus - INFO - Focus: 38.27, 1.06, 5.53
2014-09-18 13:49:31,980 - auto_focus.focus - INFO - Focus: 38.22, 1.11, 5.72
2014-09-18 13:52:33,551 - auto_focus.focus - INFO - Focus: 38.27, 1.31, 5.93
2014-09-18 13:52:41,200 - auto_focus.focus - INFO - Focus: 38.32, 1.31, 5.93
2014-09-18 13:52:48,940 - auto_focus.focus - INFO - Focus: 38.32, 1.36, 5.96
2014-09-18 13:54:58,220 - auto_focus.focus - INFO - Focus: 38.32, 1.44, 6.09
2014-09-18 13:55:05,881 - auto_focus.focus - INFO - Focus: 38.32, 1.49, 6.12
2014-09-18 13:55:13,611 - auto_focus.focus - INFO - Focus: 38.32, 1.49, 6.12
2014-09-18 13:55:26,750 - auto_focus.focus - INFO - Focus: 38.37, 1.49, 6.25
2014-09-18 13:57:25,990 - auto_focus.focus - INFO - Focus: 38.37, 1.59, 6.28
2014-09-18 13:57:33,651 - auto_focus.focus - INFO - Focus: 38.32, 1.64, 6.55
2014-09-18 13:57:41,730 - auto_focus.focus - INFO - Focus: 38.37, 1.74, 6.55
2014-09-18 13:57:49,480 - auto_focus.focus - INFO - Focus: 38.37, 1.74, 6.55
2014-09-18 13:58:20,391 - auto_focus.focus - INFO - Focus: 41.66, 2.02, 6.84
2014-09-18 13:58:27,780 - auto_focus.focus - INFO - Focus: 41.71, 2.07, 6.95
2014-09-18 13:58:35,361 - auto_focus.focus - INFO - Focus: 41.66, 2.12, 7.00
2014-09-18 13:58:42,841 - auto_focus.focus - INFO - Focus: 41.61, 2.12, 7.11
2014-09-18 14:00:05,460 - auto_focus.focus - INFO - Focus: 41.66, 2.12, 7.11
2014-09-18 14:00:12,790 - auto_focus.focus - INFO - Focus: 41.61, 2.22, 7.16
2014-09-18 14:00:20,010 - auto_focus.focus - INFO - Focus: 41.66, 2.22, 7.19
2014-09-18 14:01:40,290 - auto_focus.focus - INFO - Focus: 38.91, 5.45, 7.32
2014-09-18 14:01:48,250 - auto_focus.focus - INFO - Focus: 38.86, 5.45, 7.35
2014-09-18 14:02:07,940 - auto_focus.focus - INFO - Focus: 38.86, 5.40, 7.38
2014-09-18 14:02:15,611 - auto_focus.focus - INFO - Focus: 38.86, 5.50, 7.41
2014-09-18 14:02:27,210 - auto_focus.focus - INFO - Focus: 38.91, 5.50, 7.43
2014-09-18 14:02:39,030 - auto_focus.focus - INFO - Focus: 38.86, 5.45, 7.31
2014-09-18 14:02:54,740 - counter_trace._run - ERROR - nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 90, in _run
    counter_tr.startCounter()
  File "D:\pi3diamondnew\hardware\nidaq.py", line 203, in startCounter
    self.setCountLength(numpy.inf, max(1000, self._CountAverageLength), self._CountAverageLength)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 150, in setCountLength
    CHK(  dll.DAQmxCfgImplicitTiming( self.COTask, DAQmx_Val_ContSamps, ctypes.c_ulonglong(BufferLength))  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-18 14:02:57,161 - counter_trace._run - ERROR - nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 90, in _run
    counter_tr.startCounter()
  File "D:\pi3diamondnew\hardware\nidaq.py", line 203, in startCounter
    self.setCountLength(numpy.inf, max(1000, self._CountAverageLength), self._CountAverageLength)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 151, in setCountLength
    CHK(  dll.DAQmxCfgImplicitTiming( self.CITask, DAQmx_Val_ContSamps, ctypes.c_ulonglong(BufferLength))  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2014-09-18 14:11:28,822 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 14:11:29,891 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 14:11:34,441 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 14:11:47,721 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 14:12:03,832 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 14:12:10,721 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 14:12:11,282 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 14:12:13,842 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 14:12:14,272 - counter_trace._run - ERROR - nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
Traceback (most recent call last):
  File "D:\pi3diamondnew\measurements\counter_trace.py", line 100, in _run
    self.C = numpy.append(self.C[1:], counter_tr.Count())
  File "D:\pi3diamondnew\hardware\nidaq.py", line 220, in Count
    return self.ReadCI().mean() * self._f / self._DutyCycle
  File "D:\pi3diamondnew\hardware\nidaq.py", line 195, in ReadCI
    , ctypes.byref(self._CINread), None) )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 62, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200277: 'Invalid combination of position and offset. The position and offset specified a sample prior to the first sample acquired (sample 0).\n\nMake sure any negative read offset specified will select a valid sample when combined with the read position.'
2014-09-18 14:12:28,871 - pi3diamond.<module> - INFO - Starting logger.
2014-09-18 14:12:30,681 - emod.start - INFO - Starting Job Manager.
2014-09-18 14:12:30,681 - cron.run - INFO - Starting Cron Daemon.
2014-09-18 14:14:30,690 - auto_focus.focus - INFO - Focus: 38.48, 5.83, 9.85
2014-09-18 14:14:31,660 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0BBD69F0> is already running or in the queue.
2014-09-18 14:14:44,200 - auto_focus.focus - INFO - Focus: 38.51, 5.86, 9.74
2014-09-18 14:15:12,450 - auto_focus.focus - INFO - Focus: 38.38, 5.77, 9.66
2014-09-18 14:15:21,460 - auto_focus.focus - INFO - Focus: 38.41, 5.88, 9.66
2014-09-18 14:15:30,881 - auto_focus.focus - INFO - Focus: 38.40, 5.87, 9.71
2014-09-18 14:16:53,631 - auto_focus.focus - INFO - Focus: 38.30, 5.57, 9.84
2014-09-18 14:17:02,171 - auto_focus.focus - INFO - Focus: 38.33, 5.76, 10.05
2014-09-18 14:17:10,700 - auto_focus.focus - INFO - Focus: 38.32, 5.87, 10.16
2014-09-18 14:17:19,311 - auto_focus.focus - INFO - Focus: 38.35, 5.90, 10.08
2014-09-18 14:17:37,490 - auto_focus.focus - INFO - Focus: 38.31, 5.85, 10.13
2014-09-18 14:17:45,881 - auto_focus.focus - INFO - Focus: 38.34, 5.88, 10.10
2014-09-18 14:18:01,831 - auto_focus.focus - INFO - Focus: 38.24, 5.81, 9.38
2014-09-18 14:18:10,051 - auto_focus.focus - INFO - Focus: 38.39, 5.88, 9.38
2014-09-18 14:18:18,141 - auto_focus.focus - INFO - Focus: 38.42, 5.87, 9.38
2014-09-18 14:19:22,290 - auto_focus.focus - INFO - Focus: 38.41, 5.86, 9.41
2014-09-18 14:21:08,780 - auto_focus.focus - INFO - Focus: 38.36, 5.89, 9.54
2014-09-18 14:21:17,581 - auto_focus.focus - INFO - Focus: 38.39, 5.96, 9.59
2014-09-18 14:21:26,020 - auto_focus.focus - INFO - Focus: 38.34, 5.99, 9.72
2014-09-18 14:21:35,470 - auto_focus.focus - INFO - Focus: 38.37, 6.02, 9.69
2014-09-18 14:22:33,980 - auto_focus.focus - INFO - Focus: 38.36, 6.05, 9.53
2014-09-18 14:22:42,430 - auto_focus.focus - INFO - Focus: 38.39, 6.04, 9.50
2014-09-18 14:22:50,790 - auto_focus.focus - INFO - Focus: 38.38, 6.07, 9.63
2014-09-18 14:23:57,301 - auto_focus.focus - INFO - Focus: 38.37, 6.14, 9.52
2014-09-18 14:24:05,770 - auto_focus.focus - INFO - Focus: 38.36, 6.09, 9.52
2014-09-18 14:24:21,391 - auto_focus.focus - INFO - Focus: 38.15, 6.00, 9.28
2014-09-18 14:24:29,841 - auto_focus.focus - INFO - Focus: 38.38, 5.99, 8.88
2014-09-18 14:24:38,010 - auto_focus.focus - INFO - Focus: 38.41, 5.98, 8.91
2014-09-18 14:24:46,321 - auto_focus.focus - INFO - Focus: 38.40, 5.97, 8.80
2014-09-18 14:24:55,720 - auto_focus.focus - INFO - Focus: 38.43, 5.92, 8.83
2014-09-18 14:27:04,151 - auto_focus.focus - INFO - Focus: 38.42, 5.91, 9.12
2014-09-18 14:27:12,502 - auto_focus.focus - INFO - Focus: 38.41, 6.02, 9.15
2014-09-18 14:28:06,441 - auto_focus.focus - INFO - Focus: 38.36, 6.09, 9.20
2014-09-18 14:28:14,792 - auto_focus.focus - INFO - Focus: 38.39, 6.08, 9.17
2014-09-18 14:28:34,272 - auto_focus.focus - INFO - Focus: 38.18, 5.91, 8.93
2014-09-18 14:28:42,411 - auto_focus.focus - INFO - Focus: 38.41, 5.98, 8.74
2014-09-18 14:28:50,552 - auto_focus.focus - INFO - Focus: 38.44, 5.89, 8.58
2014-09-18 14:28:58,812 - auto_focus.focus - INFO - Focus: 38.39, 5.92, 8.50
2014-09-18 14:29:47,631 - auto_focus.focus - INFO - Focus: 38.38, 5.75, 8.69
2014-09-18 14:29:55,832 - auto_focus.focus - INFO - Focus: 38.41, 5.86, 8.80
2014-09-18 14:30:04,062 - auto_focus.focus - INFO - Focus: 38.40, 5.93, 8.99
2014-09-18 14:30:58,302 - auto_focus.focus - INFO - Focus: 38.43, 5.80, 8.91
2014-09-18 14:31:06,512 - auto_focus.focus - INFO - Focus: 38.42, 5.75, 8.91
2014-09-18 14:31:45,842 - auto_focus.focus - INFO - Focus: 38.33, 5.74, 8.88
2014-09-18 14:31:54,151 - auto_focus.focus - INFO - Focus: 38.36, 5.73, 8.85
2014-09-18 14:32:13,401 - auto_focus.focus - INFO - Focus: 38.39, 5.96, 8.53
2014-09-18 14:32:22,012 - auto_focus.focus - INFO - Focus: 38.38, 5.87, 8.42
2014-09-18 14:33:56,351 - auto_focus.focus - INFO - Focus: 38.45, 5.82, 8.63
2014-09-18 14:34:04,871 - auto_focus.focus - INFO - Focus: 38.44, 5.85, 8.76
2014-09-18 14:35:11,471 - auto_focus.focus - INFO - Focus: 38.43, 5.88, 8.68
2014-09-18 14:35:19,792 - auto_focus.focus - INFO - Focus: 38.42, 5.91, 8.68
2014-09-18 14:36:00,171 - auto_focus.focus - INFO - Focus: 38.37, 5.90, 8.60
2014-09-18 14:36:08,792 - auto_focus.focus - INFO - Focus: 38.40, 5.89, 8.65
2014-09-18 14:36:56,111 - auto_focus.focus - INFO - Focus: 38.43, 5.96, 8.57
2014-09-18 14:37:04,542 - auto_focus.focus - INFO - Focus: 38.38, 5.95, 8.46
2014-09-18 14:37:16,971 - auto_focus.focus - INFO - Focus: 38.41, 5.94, 8.57
2014-09-18 14:37:25,921 - auto_focus.focus - INFO - Focus: 38.44, 5.89, 8.38
2014-09-18 14:37:34,332 - auto_focus.focus - INFO - Focus: 38.47, 6.00, 8.51
2014-09-18 14:37:54,312 - auto_focus.focus - INFO - Focus: 38.42, 5.91, 8.43
2014-09-18 14:38:02,762 - auto_focus.focus - INFO - Focus: 38.45, 5.90, 8.43
2014-09-18 14:38:13,522 - auto_focus.focus - INFO - Focus: 38.40, 5.89, 8.35
2014-09-18 14:38:22,601 - auto_focus.focus - INFO - Focus: 38.43, 5.88, 8.46
2014-09-18 14:39:45,153 - auto_focus.focus - INFO - Focus: 38.46, 5.95, 8.49
2014-09-18 14:39:53,602 - auto_focus.focus - INFO - Focus: 38.45, 5.90, 8.30
2014-09-18 14:40:03,862 - auto_focus.focus - INFO - Focus: 38.44, 5.89, 8.49
2014-09-18 14:43:39,733 - auto_focus.focus - INFO - Focus: 33.05, 27.24, 8.14
2014-09-18 14:43:47,842 - auto_focus.focus - INFO - Focus: 32.92, 27.15, 8.11
2014-09-18 14:43:55,923 - auto_focus.focus - INFO - Focus: 32.91, 27.18, 8.14
2014-09-18 14:44:11,163 - auto_focus.focus - INFO - Focus: 32.90, 27.17, 8.25
2014-09-18 14:44:20,213 - auto_focus.focus - INFO - Focus: 32.89, 27.24, 8.30
2014-09-18 14:44:28,532 - auto_focus.focus - INFO - Focus: 32.88, 27.19, 8.33
2014-09-18 14:44:39,082 - auto_focus.focus - INFO - Focus: 32.99, 27.18, 8.38
2014-09-18 14:44:47,322 - auto_focus.focus - INFO - Focus: 32.94, 27.17, 8.19
2014-09-18 14:44:55,782 - auto_focus.focus - INFO - Focus: 32.93, 27.20, 8.19
2014-09-18 14:45:05,493 - auto_focus.focus - INFO - Focus: 32.92, 27.19, 8.30
2014-09-18 14:45:41,503 - auto_focus.focus - INFO - Focus: 35.57, 30.97, 8.22
2014-09-18 14:45:49,552 - auto_focus.focus - INFO - Focus: 35.60, 30.92, 8.19
2014-09-18 14:45:57,642 - auto_focus.focus - INFO - Focus: 35.59, 30.99, 8.22
2014-09-18 14:46:58,773 - auto_focus.focus - INFO - Focus: 35.62, 30.98, 8.06
2014-09-18 14:47:17,403 - auto_focus.focus - INFO - Focus: 35.61, 30.93, 8.11
2014-09-18 14:47:25,933 - auto_focus.focus - INFO - Focus: 35.64, 30.96, 8.24
2014-09-18 14:50:08,523 - auto_focus.focus - INFO - Focus: 35.59, 30.91, 8.24
2014-09-18 14:55:07,823 - auto_focus.focus - INFO - Focus: 40.53, 38.61, 8.13
2014-09-18 14:55:15,864 - auto_focus.focus - INFO - Focus: 40.52, 38.76, 8.40
2014-09-18 14:55:23,834 - auto_focus.focus - INFO - Focus: 40.59, 38.83, 8.51
2014-09-18 15:08:26,105 - auto_focus.focus - INFO - Focus: 36.91, 37.92, 8.70
2014-09-18 15:08:34,545 - auto_focus.focus - INFO - Focus: 36.90, 37.91, 8.54
2014-09-18 15:12:16,005 - auto_focus.focus - INFO - Focus: 40.61, 38.75, 8.81
2014-09-18 15:12:24,134 - auto_focus.focus - INFO - Focus: 40.56, 38.74, 9.08
2014-09-18 15:29:42,286 - auto_focus.focus - INFO - Focus: 40.58, 38.72, 9.11
2014-09-18 15:29:50,536 - auto_focus.focus - INFO - Focus: 40.57, 38.75, 9.22
2014-09-18 15:29:58,927 - auto_focus.focus - INFO - Focus: 40.56, 38.74, 9.22
2014-09-18 15:39:53,888 - auto_focus.focus - INFO - Focus: 40.51, 38.69, 9.49
2014-09-18 15:40:03,207 - auto_focus.focus - INFO - Focus: 40.58, 38.72, 9.49
2014-09-18 15:49:05,328 - auto_focus.focus - INFO - Focus: 40.53, 38.67, 9.62
2014-09-18 15:49:13,618 - auto_focus.focus - INFO - Focus: 40.52, 38.66, 9.73
2014-09-18 15:49:21,907 - auto_focus.focus - INFO - Focus: 40.55, 38.69, 9.78
2014-09-18 15:49:31,227 - auto_focus.focus - INFO - Focus: 40.50, 38.68, 9.67
2014-09-18 15:49:40,648 - auto_focus.focus - INFO - Focus: 40.53, 38.63, 9.70
2014-09-18 15:59:10,019 - auto_focus.focus - INFO - Focus: 40.52, 38.70, 9.89
2014-09-18 16:04:45,059 - auto_focus.focus - INFO - Focus: 36.89, 37.83, 9.89
2014-09-18 16:04:53,059 - auto_focus.focus - INFO - Focus: 36.84, 37.78, 9.62
2014-09-18 16:05:01,930 - auto_focus.focus - INFO - Focus: 36.83, 37.81, 9.59
2014-09-18 16:05:11,200 - auto_focus.focus - INFO - Focus: 36.86, 37.84, 9.78
2014-09-18 16:05:23,500 - auto_focus.focus - INFO - Focus: 36.85, 37.87, 9.78
2014-09-18 16:24:25,811 - auto_focus.focus - INFO - Focus: 36.88, 38.06, 10.31
2014-09-18 16:24:59,480 - auto_focus.focus - INFO - Focus: 36.83, 37.93, 10.31
2014-09-18 16:25:07,500 - auto_focus.focus - INFO - Focus: 36.86, 37.92, 10.44
2014-09-18 16:25:15,700 - auto_focus.focus - INFO - Focus: 36.89, 37.75, 10.09
2014-09-18 16:25:38,401 - auto_focus.focus - INFO - Focus: 36.80, 37.86, 10.22
2014-09-18 16:25:46,361 - auto_focus.focus - INFO - Focus: 36.83, 37.85, 10.33
2014-09-18 16:25:54,460 - auto_focus.focus - INFO - Focus: 36.82, 37.88, 10.14
2014-09-18 16:26:19,522 - auto_focus.focus - INFO - Focus: 36.85, 37.79, 10.11
2014-09-18 16:33:22,252 - auto_focus.focus - INFO - Focus: 40.46, 38.67, 10.40
2014-09-18 16:33:33,322 - auto_focus.focus - INFO - Focus: 40.49, 38.66, 10.53
2014-09-18 16:37:25,881 - auto_focus.focus - INFO - Focus: 40.49, 38.62, 10.66
2014-09-18 16:37:34,522 - auto_focus.focus - INFO - Focus: 40.44, 38.65, 10.77
2014-09-18 16:38:07,703 - auto_focus.focus - INFO - Focus: 40.43, 38.60, 10.45
2014-09-18 16:38:16,792 - auto_focus.focus - INFO - Focus: 40.46, 38.67, 10.82
2014-09-18 16:43:16,792 - auto_focus.focus - INFO - Focus: 40.45, 38.58, 10.36
2014-09-18 16:43:26,673 - auto_focus.focus - INFO - Focus: 40.44, 38.57, 10.57
2014-09-19 10:01:07,753 - auto_focus.focus - INFO - Focus: 38.83, 38.31, 10.46
2014-09-19 10:01:15,844 - auto_focus.focus - INFO - Focus: 38.78, 38.42, 10.22
2014-09-19 10:04:33,523 - auto_focus.focus - INFO - Focus: 38.80, 38.35, 10.25
