2017-09-19 14:44:41,855 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 14:50:34,440 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 14:52:23,486 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 14:53:38,671 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 14:53:38,822 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 14:53:38,822 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 14:53:38,832 - toolkit.toolkit - INFO - Could not import traits UI backend 'wx'
2017-09-19 14:53:38,832 - toolkit.toolkit - ERROR - No module named wx
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\__init__.py", line 26, in <module>
    import toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\toolkit.py", line 30, in <module>
    import wx
ImportError: No module named wx
2017-09-19 14:57:41,880 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 14:57:42,759 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 14:57:42,759 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 14:57:42,759 - toolkit.toolkit - INFO - Could not import traits UI backend 'wx'
2017-09-19 14:57:42,759 - toolkit.toolkit - ERROR - No module named wx
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\__init__.py", line 26, in <module>
    import toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\toolkit.py", line 30, in <module>
    import wx
ImportError: No module named wx
2017-09-19 15:02:04,368 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 15:02:04,578 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 15:02:04,578 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 15:02:04,578 - toolkit.toolkit - INFO - Could not import traits UI backend 'wx'
2017-09-19 15:02:04,578 - toolkit.toolkit - ERROR - No module named wx
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\__init__.py", line 26, in <module>
    import toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\toolkit.py", line 30, in <module>
    import wx
ImportError: No module named wx
2017-09-19 15:05:25,200 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 15:05:25,331 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 15:05:25,331 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 15:05:25,331 - toolkit.toolkit - INFO - Could not import traits UI backend 'wx'
2017-09-19 15:05:25,341 - toolkit.toolkit - ERROR - No module named wx
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\__init__.py", line 26, in <module>
    import toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\toolkit.py", line 30, in <module>
    import wx
ImportError: No module named wx
2017-09-19 15:07:16,232 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 15:07:16,381 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 15:07:16,381 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 15:07:16,391 - toolkit.toolkit - INFO - Could not import traits UI backend 'wx'
2017-09-19 15:07:16,391 - toolkit.toolkit - ERROR - No module named wx
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\__init__.py", line 26, in <module>
    import toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\wx\toolkit.py", line 30, in <module>
    import wx
ImportError: No module named wx
2017-09-19 15:11:11,536 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 15:11:12,476 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 15:11:12,476 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 15:50:38,322 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 15:50:38,631 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 15:50:38,631 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 15:58:49,010 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 15:58:49,240 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 15:58:49,240 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 17:39:26,118 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 17:39:27,029 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 17:39:27,039 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 17:39:31,108 - emod.start - INFO - Starting Job Manager.
2017-09-19 17:39:31,118 - cron.run - INFO - Starting Cron Daemon.
2017-09-19 17:42:57,684 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 17:42:57,835 - toolkit.toolkit - INFO - Could not import traits UI backend 'qt4'
2017-09-19 17:42:57,835 - toolkit.toolkit - ERROR - Cannot import PySide or PyQt4
Traceback (most recent call last):
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\Users\pi3\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py", line 18, in <module>
    import pyface.qt
  File "C:\Users\pi3\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line 37, in <module>
    raise ImportError('Cannot import PySide or PyQt4')
ImportError: Cannot import PySide or PyQt4
2017-09-19 17:42:58,454 - emod.start - INFO - Starting Job Manager.
2017-09-19 17:42:58,454 - cron.run - INFO - Starting Cron Daemon.
2017-09-19 17:46:40,859 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 17:46:42,119 - emod.start - INFO - Starting Job Manager.
2017-09-19 17:46:42,119 - cron.run - INFO - Starting Cron Daemon.
2017-09-19 18:05:14,674 - pi3diamond.<module> - INFO - Starting logger.
2017-09-19 18:05:15,384 - emod.start - INFO - Starting Job Manager.
2017-09-19 18:05:15,384 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 10:32:50,516 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 10:32:57,105 - emod.start - INFO - Starting Job Manager.
2017-09-20 10:32:57,117 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 10:34:51,154 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 10:34:51,858 - emod.start - INFO - Starting Job Manager.
2017-09-20 10:34:51,859 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 10:39:08,184 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 10:39:08,878 - emod.start - INFO - Starting Job Manager.
2017-09-20 10:39:08,878 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 11:05:30,148 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 11:05:30,897 - emod.start - INFO - Starting Job Manager.
2017-09-20 11:05:30,898 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 12:18:18,282 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 12:18:23,894 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 12:18:26,016 - emod.start - INFO - Starting Job Manager.
2017-09-20 12:18:26,026 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 12:31:48,619 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 12:31:49,369 - emod.start - INFO - Starting Job Manager.
2017-09-20 12:31:49,371 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 13:25:55,848 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 13:25:56,605 - emod.start - INFO - Starting Job Manager.
2017-09-20 13:25:56,607 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 14:27:58,516 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 14:27:59,321 - emod.start - INFO - Starting Job Manager.
2017-09-20 14:27:59,322 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 14:30:42,492 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 14:30:43,211 - emod.start - INFO - Starting Job Manager.
2017-09-20 14:30:43,211 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 14:36:06,052 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 14:36:06,763 - emod.start - INFO - Starting Job Manager.
2017-09-20 14:36:06,763 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 14:58:08,940 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 14:58:09,707 - emod.start - INFO - Starting Job Manager.
2017-09-20 14:58:09,709 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 15:29:17,114 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 15:29:17,864 - emod.start - INFO - Starting Job Manager.
2017-09-20 15:29:17,864 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 15:32:10,914 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 15:32:11,644 - emod.start - INFO - Starting Job Manager.
2017-09-20 15:32:11,644 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 15:33:34,957 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 15:33:35,828 - emod.start - INFO - Starting Job Manager.
2017-09-20 15:33:35,828 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 15:43:25,286 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 15:43:26,026 - emod.start - INFO - Starting Job Manager.
2017-09-20 15:43:26,026 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 15:43:52,006 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 15:43:53,207 - emod.start - INFO - Starting Job Manager.
2017-09-20 15:43:53,207 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 15:46:44,798 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 15:46:45,717 - emod.start - INFO - Starting Job Manager.
2017-09-20 15:46:45,717 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 17:51:38,075 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 17:51:38,744 - emod.start - INFO - Starting Job Manager.
2017-09-20 17:51:38,744 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 18:31:52,575 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 18:31:53,335 - emod.start - INFO - Starting Job Manager.
2017-09-20 18:31:53,335 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 18:39:06,809 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 18:39:07,539 - emod.start - INFO - Starting Job Manager.
2017-09-20 18:39:07,539 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 18:42:56,598 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 18:42:57,288 - emod.start - INFO - Starting Job Manager.
2017-09-20 18:42:57,288 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 18:43:05,438 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 18:43:06,108 - emod.start - INFO - Starting Job Manager.
2017-09-20 18:43:06,118 - cron.run - INFO - Starting Cron Daemon.
2017-09-20 19:05:46,285 - pi3diamond.<module> - INFO - Starting logger.
2017-09-20 19:05:47,015 - emod.start - INFO - Starting Job Manager.
2017-09-20 19:05:47,015 - cron.run - INFO - Starting Cron Daemon.
